### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lagaleno** [gilbonett/PortfolioPedro#1]
Boa tarde Pedro! Só passando para deixar feedback sobre seu site: achei muito bom! Soube usar as tags HTML que vimos, além de usar também uma navegação já usando para fazer tudo em uma página só! Muito bom! Parabéns :)

**Comment by gilbonett** [comment]
Obrigado pelo Feedback essa interação é muito importante para mim, adicionei o Formulário na pagina tinha duvidas de como fazer e na aula ficou mais claro com o conteúdo que estudei. Obrigado, continue sendo incrivel.
